package com.enviro.assessment.junior.siseko_makomazi.model;

import jakarta.persistence.*;

/**
 * Represents an investor in the system.
 * Contains personal information including name, email, and age.
 * Age is important for business rule validation (retirement withdrawals require age > 65).
 */
@Entity
public class Investor {
    // id is declared here as the primary key generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // firstName, lastName, and email are declared here as basic investor profile fields.
    private String firstName;
    private String lastName;
    private String email;
    
    // Age is critical for business rules - retirement products require age > 65
    private int age;

    // Getters expose private fields to controllers/JPA; setters allow JPA and services to assign values.
    public Long getId() { return id; }
    // id is declared as the setter parameter and replaces this entity's id value.
    public void setId(Long id) { this.id = id; }
    
    public String getFirstName() { return firstName; }
    // v is declared as the setter parameter and represents the new first name.
    public void setFirstName(String v) { this.firstName = v; }
    
    public String getLastName() { return lastName; }
    // v is declared as the setter parameter and represents the new last name.
    public void setLastName(String v) { this.lastName = v; }
    
    public String getEmail() { return email; }
    // v is declared as the setter parameter and represents the new email address.
    public void setEmail(String v) { this.email = v; }
    
    public int getAge() { return age; }
    // v is declared as the setter parameter and represents the investor's age.
    public void setAge(int v) { this.age = v; }
}
