package com.enviro.assessment.junior.siseko_makomazi.model;

import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.List;

/**
 * Represents an investment portfolio belonging to an investor.
 * Contains a collection of products (investment funds) that the investor holds.
 * Eager fetching used to load products with portfolio for API responses.
 */
@Entity
public class Portfolio {
    // id is declared here as the portfolio primary key generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Many-to-one relationship with Investor - eager fetch to always load investor data
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "investor_id")
    private Investor investor;

    // Portfolio name (e.g., "Thabo Retirement Portfolio")
    private String name;

    // One-to-many relationship with Products - cascade all operations, eager fetch for API responses
    // JsonManagedReference prevents infinite recursion in JSON serialization
    @OneToMany(mappedBy = "portfolio", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JsonManagedReference
    private List<Product> products;

    // Getters expose fields for JSON/JPA; setters allow JPA and services to populate the entity.
    public Long getId() { return id; }
    // id is declared as the setter parameter and represents the database ID.
    public void setId(Long id) { this.id = id; }
    
    public Investor getInvestor() { return investor; }
    // i is declared as the setter parameter and represents the portfolio owner.
    public void setInvestor(Investor i) { this.investor = i; }
    
    public String getName() { return name; }
    // n is declared as the setter parameter and represents the portfolio name.
    public void setName(String n) { this.name = n; }
    
    public List<Product> getProducts() { return products; }
    // p is declared as the setter parameter and represents the products inside the portfolio.
    public void setProducts(List<Product> p) { this.products = p; }
}
