package com.enviro.assessment.junior.siseko_makomazi.model;

import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonBackReference;
import java.math.BigDecimal;

/**
 * Represents an investment product within a portfolio.
 * Products can be of type RETIREMENT or SAVINGS.
 * Type determines business rules for withdrawals (retirement requires age > 65).
 */
@Entity
public class Product {
    // id is declared here as the product primary key generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Many-to-one relationship with Portfolio
    // JsonBackReference prevents infinite recursion in JSON serialization
    @ManyToOne
    @JoinColumn(name = "portfolio_id")
    @JsonBackReference
    private Portfolio portfolio;

    // Product type: RETIREMENT or SAVINGS
    // RETIREMENT products have age restrictions for withdrawals
    private String type;
    
    // Product name (e.g., "Pension Fund A", "Money Market")
    private String name;
    
    // Current balance available for withdrawal
    private BigDecimal balance;

    // Getters expose fields for API responses; setters allow JPA and services to update the entity.
    public Long getId() { return id; }
    // id is declared as the setter parameter and represents the product database ID.
    public void setId(Long id) { this.id = id; }
    
    public Portfolio getPortfolio() { return portfolio; }
    // p is declared as the setter parameter and represents the parent portfolio.
    public void setPortfolio(Portfolio p) { this.portfolio = p; }
    
    public String getType() { return type; }
    // t is declared as the setter parameter and represents RETIREMENT or SAVINGS.
    public void setType(String t) { this.type = t; }
    
    public String getName() { return name; }
    // n is declared as the setter parameter and represents the product name.
    public void setName(String n) { this.name = n; }
    
    public BigDecimal getBalance() { return balance; }
    // b is declared as the setter parameter and represents the current product balance.
    public void setBalance(BigDecimal b) { this.balance = b; }
}
